server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location /.well-known/ {
        default_type application/json;
    }

    location /share/ {
        try_files $uri /share/index.html;
    }

    location /delete-account {
        try_files $uri /delete-account/index.html;
    }

    location /privacy {
        try_files $uri /privacy/index.html;
    }
}
